# Required for automatically migrating the config.
# Don't change this value.
config-version: 1

# The name of the primary currency.
# Must match a key under the 'currencies' section.
# Legacy economy providers will always use this currency.
default-currency: gold

# Default format rules to apply to currencies.
# These can be overridden as individual currencies.
default-number-formatter:
  # How digits are grouped before the decimal 
  grouping:
    # Amount of digits per group.
    # Set to 0 for no grouping.
    # Default: 3
    group-size: 3
    
    # String or symbol used to separate a group.
    # Setting to empty string ('') effectively means no grouping.
    # Default: ''
    separator: ','
  
  # How the fractional part should be displayed.
  # Does not affect how it is stored.
  decimal:
    # Whether the displayed amount should round to the nearest place it can show.
    # If false, will always round down.
    # Default: true
    round: true

    # How many places to show after the decimal.
    # If 0, the formatter will drop any separator.
    # Default: 2
    places: 2

    # String or symbol used to separate the integer part from the fractional part.
    # Default: '.'
    separator: '.'

# ---------------------------
# Currency configurations
# ---------------------------

currencies:
  # # Begin a currency section. You can use any string as a key in place of 'currency-name'.
  # currency-name:
  #   # Singular form of the display name.
  #   # If not provided, JConomy will attempt to fallback to the plural name.
  #   display-name-singular: Jelly Coin
  #   
  #   # Plural form of the display name.
  #   # If not provided, JConomy will attempt to fallback to the singlular name.
  #   display-name-plural: Jelly Coins
  #
  #   # Symbol to use next to the currency.
  #   # Can use '' for no symbol.
  #   # Default: ''
  #   symbol: '$'
  #
  #   # How the currency display string is assembled.
  #   # The following placeholders are supported:
  #   # - %amount_raw% : The raw, unformatted number. Could be ugly
  #   # - %amount_formatted% : The number formatted by the number-formatter. Usually recommended for showing amounts.
  #   # - %symbol% : The currency symbol
  #   # - %display_name% : The display-name-singular, if the rounded amount is 1; else, the display-name-plural.
  #   # Default: '%symbol%%amount_formatted%'
  #   format-string: '%symbol%%amount_formatted%'
  #
  #   # Format rules for how this currency is displayed.
  #   # You can omit any of these rules if you would like to use the defaults configured above.
  #   number-formatter:
  #     # How digits are grouped before the decimal 
  #     grouping:
  #       # Amount of digits per group.
  #       # Set to 0 for no grouping.
  #       # Default: 3
  #       group-size: 3
  #
  #       # String or symbol used to separate a group.
  #       # Setting to empty string ('') effectively means no grouping.
  #       # Default: ''
  #       separator: ''
  #     
  #     # How the fractional part should be displayed.
  #     # Does not affect how it is stored.
  #     decimal:
  #       # Whether the displayed amount should round to the nearest place it can show.
  #       # If false, will always round down.
  #       # Default: true
  #       round: true
  #       # How many places to show after the decimal.
  #       # If 0, the formatter will drop any separator.
  #       # Default: 2
  #       places: 2
  #       # String or symbol used to separate the integer part from the fractional part.
  #       # Default: '.'
  #       separator: '.'

  gold:
    display-name-singular: Gold Coin
    display-name-plural: Gold Coins
    symbol: '&6🪙ɢᴏʟᴅ'
    format-string: '%amount% %symbol%'
    number-formatter:
      decimal:
        places: 0

# Player balance cache settings.
cache:
  # Configures how many of the most recently accessed players to cache.
  # For fine-tuning performance on very large servers.
  # Default: 10,000.
  lru-limit: 10000
